# Author
author:
  name: Albert Blanco
  email:
  url: albrtbc.github.io

# Site settings
title: Albert Blanco
description: >
    A place where I can drop code snippets, tech articles and how-to's of various projects I'm working on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://albrtbc.github.io" # the base hostname & protocol for your site

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# social media
github_username:  albrtbc
github_url: https://github.com/albrtbc
youtube_username: 
youtube_url: 

# analytics
google_analytics: UA-113522886-1

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

highlighter: rouge

# page settings
paginate: 5
paginate_path: "/blog/page:num"

enableTags: true
tagarray: []

# gems
gems: [jekyll-paginate, jekyll-gist]
